# Generated by Django 5.2.7 on 2025-10-27 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hexagram',
            fields=[
                ('hexagram_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='卦番号 (1-64)')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='卦名 (例: 乾為天)')),
                ('yomi', models.CharField(max_length=10, verbose_name='読み方 (例: けんいてん)')),
                ('upper_trigram', models.CharField(choices=[('乾', '天'), ('坤', '地'), ('震', '雷'), ('巽', '風'), ('坎', '水'), ('離', '火'), ('艮', '山'), ('兌', '沢')], max_length=2, verbose_name='上卦')),
                ('lower_trigram', models.CharField(choices=[('乾', '天'), ('坤', '地'), ('震', '雷'), ('巽', '風'), ('坎', '水'), ('離', '火'), ('艮', '山'), ('兌', '沢')], max_length=2, verbose_name='下卦')),
                ('image_desc', models.TextField(verbose_name='卦の象 (イメージ)')),
                ('gua_ci_meaning', models.TextField(verbose_name='卦辞の基本解釈')),
                ('fortune_summary', models.TextField(verbose_name='運勢（総合的な流れ）')),
                ('rating', models.CharField(choices=[('大吉', '大吉'), ('吉', '吉'), ('中吉', '中吉'), ('小吉', '小吉'), ('平', '平'), ('小凶', '小凶'), ('凶', '凶'), ('大凶', '大凶')], default='平', max_length=4, verbose_name='総合吉凶')),
            ],
            options={
                'verbose_name': '易卦 (64卦)',
                'verbose_name_plural': '易卦 (64卦)',
                'ordering': ['hexagram_id'],
            },
        ),
        migrations.CreateModel(
            name='DivinationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='占い日時')),
                ('question', models.CharField(blank=True, max_length=255, null=True, verbose_name='質問内容')),
                ('changing_lines_list', models.CharField(blank=True, max_length=10, null=True, verbose_name='変爻のリスト')),
                ('changing_hexagram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_changing', to='uranai_data.hexagram', verbose_name='之卦')),
                ('original_hexagram', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results_original', to='uranai_data.hexagram', verbose_name='本卦')),
            ],
            options={
                'verbose_name': '占い結果履歴',
                'verbose_name_plural': '占い結果履歴',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='LineText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_position', models.IntegerField(choices=[(1, '初爻'), (2, '二爻'), (3, '三爻'), (4, '四爻'), (5, '五爻'), (6, '上爻')], verbose_name='爻の位置')),
                ('yao_ci_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='爻辞 (古典文言)')),
                ('yao_ci_meaning', models.TextField(verbose_name='爻辞の現代語解釈')),
                ('changing_line_special_meaning', models.TextField(blank=True, null=True, verbose_name='変爻時の特別な意味・アドバイス')),
                ('hexagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='uranai_data.hexagram', verbose_name='所属卦')),
            ],
            options={
                'verbose_name': '爻辞',
                'verbose_name_plural': '爻辞',
                'ordering': ['hexagram', 'line_position'],
                'unique_together': {('hexagram', 'line_position')},
            },
        ),
        migrations.CreateModel(
            name='ThemeAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('恋愛', '恋愛'), ('仕事', '仕事'), ('金運', '金運'), ('健康', '健康'), ('対人', '対人関係'), ('願望', '願望・目標')], max_length=4, verbose_name='テーマ')),
                ('advice_text', models.TextField(verbose_name='テーマ別詳細アドバイス')),
                ('keywords', models.CharField(blank=True, max_length=100, null=True, verbose_name='キーワード')),
                ('hexagram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_advices', to='uranai_data.hexagram', verbose_name='対象卦')),
            ],
            options={
                'verbose_name': 'テーマ別アドバイス',
                'verbose_name_plural': 'テーマ別アドバイス',
                'unique_together': {('hexagram', 'theme')},
            },
        ),
    ]
